//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrdering.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string CompanyCode { get; set; }
        public string Addresss { get; set; }
        public Nullable<int> NumOfShifts { get; set; }
        public Nullable<System.TimeSpan> ShiftOneStart { get; set; }
        public Nullable<System.TimeSpan> ShiftOneEnd { get; set; }
        public Nullable<System.TimeSpan> ShiftTwoStart { get; set; }
        public Nullable<System.TimeSpan> ShiftTwoEnd { get; set; }
        public Nullable<System.TimeSpan> ShiftThreeStart { get; set; }
        public Nullable<System.TimeSpan> ShiftThreeEnd { get; set; }
        public Nullable<System.TimeSpan> DeliveryOne { get; set; }
        public Nullable<System.TimeSpan> DeliveryTwo { get; set; }
        public Nullable<System.TimeSpan> DeliveryThree { get; set; }
        public Nullable<System.TimeSpan> LockOne { get; set; }
        public Nullable<System.TimeSpan> LockTwo { get; set; }
        public Nullable<System.TimeSpan> LockThree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
