//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrdering.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMeal
    {
        public long MenuId { get; set; }
        public long MealId { get; set; }
        public string DayOfWeek { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
